# Generated by Django 4.2.3 on 2023-08-05 09:03

from django.db import migrations, models
import max.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='withoutvehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('time_in', models.TimeField(default=max.models.get_current_time)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('today', models.DateField(auto_now_add=True)),
                ('idphoto', models.ImageField(blank=True, null=True, upload_to='Idphotowithoutvehicle/')),
                ('Exit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='withvehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_registration', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('time_in', models.TimeField(default=max.models.get_current_time)),
                ('time_out', models.TimeField(null=True)),
                ('today', models.DateField(auto_now_add=True)),
                ('idphoto', models.ImageField(blank=True, null=True, upload_to='IDphotowithvehicle/')),
                ('vehiclephoto', models.ImageField(blank=True, null=True, upload_to='Vehiclephoto/')),
                ('Exit', models.BooleanField(default=False)),
            ],
        ),
    ]
