# Generated by Django 4.2.3 on 2023-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutvehicle',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
