# Generated by Django 4.2.3 on 2023-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0002_alter_withoutvehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='withoutvehicle',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withvehicle',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
