# Generated by Django 4.2.3 on 2023-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0003_withoutvehicle_time_spent_withvehicle_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutvehicle',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
