# Generated by Django 4.2.3 on 2023-07-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0030_alter_withoutvehicle_id_picture_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withoutvehicle',
            old_name='id_picture_front',
            new_name='idphoto',
        ),
        migrations.RenameField(
            model_name='withvehicle',
            old_name='id_picture_front1',
            new_name='idphoto',
        ),
        migrations.RenameField(
            model_name='withvehicle',
            old_name='id_picture_front2',
            new_name='vehiclephoto',
        ),
    ]
