# Generated by Django 4.2.3 on 2023-07-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0031_rename_id_picture_front_withoutvehicle_idphoto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withoutvehicle',
            old_name='time_updated',
            new_name='Exit',
        ),
        migrations.RenameField(
            model_name='withvehicle',
            old_name='time_updated',
            new_name='Exit',
        ),
    ]
